module.exports = {
  logo: {
    csssr: '#__next > footer > div.top-content > div > a',
  },
  link: {
    changeLocal: '[data-testid="Footer:link.language-link"]',
    estonia: '[data-testid="Footer:text:address.title.estonia"]',
    email: '[data-testid="Footer:link:email"]',
    telSingapore: '[data-testid="Footer:link:address.phone.singapore"]',
    telRussia: '[data-testid="Footer:link:address.phone.russia"]',
    telRussiaTwo: '[data-testid="Footer:link:address.phone.russia_2"]',
    outsourcing: '[data-testid="Footer:link:web-development"]',
    outsourcingEn: '[data-testid="Footer:link:outsourcing"]',
    backendAndDevops: '[data-testid="Footer:link:backend"]',
    mvp: '[data-testid="Footer:link:mvp"]',
    fintech: '[data-testid="Footer:link:fintech"]',
    informationTechnology: '[data-testid="Footer:link:information"]',
    ecommerce: '[data-testid="Footer:link:eCommerce"]',
    mediAndMarketing: '[data-testid="Footer:link:mediaAndMarketing"]',
    techStack: '[data-testid="Footer:link:technologies"]',
    wayOfWork: '[data-testid="Footer:link:wayOfWork"]',
    coreValues: '[data-testid="Footer:link:coreValues"]',
    ourProjects: '[data-testid="Footer:link:outsourcing"]',
    projects: '[data-testid="Footer:link:projects"]',
    LMS: '[data-testid="Footer:link:lms"]',
    trackingSoftware: '[data-testid="Footer:link:tracker"]',
    jobs: '[data-testid="Footer:link:careers"]',
    blog: '[data-testid="Footer:link:blog"]',
    contacts: '[data-testid="Footer:link:contactUs"]',
    jobsEn: '[data-testid="Footer:link:careers"]',
    blogEn: '[data-testid="Footer:link:blog"]',
    contactsEN: '[data-testid="Footer:link:contactUs"]',
    languageLink: '.link-text.css-q0ryfa.epkww9c0',
  },
  block: {
    footer: '[data-testid="Footer:block:DoubleBottom"]',
    map: '.map',
    bottomContent: '[data-testid="Footer:block.bottom-content"]',
  },
  text: {
    singaporeAddress: '[data-testid="Footer:text:address.singapore"]',
    russianAddress: '[data-testid="Footer:text:address.russia"]',
    russianAddressTwo: '[data-testid="Footer:text:address.russia_2"]',
    estoniaAddress: '[data-testid="Footer:text:address.estonia"]',
    SingaporeTime: '#site-footer > div.css-z4lv1x.ellxpbm0.is_visible > div.css-1r52kff.e1rf1ndj0 > div.address-item.address_singapore > p.time.css-1btcud5-Text-Text.e1rn94vo0',
    RussiaTime: '#site-footer > div.css-z4lv1x.ellxpbm0.is_visible > div.css-1r52kff.e1rf1ndj0 > div.address-item.address_russia > p.time.css-1btcud5-Text-Text.e1rn94vo0',
    RussiaTimeTo: '#site-footer > div.css-z4lv1x.ellxpbm0.is_visible > div.css-1r52kff.e1rf1ndj0 > div.address-item.address_russia_2 > p.time.css-1btcud5-Text-Text.e1rn94vo0',
    EstoniaTime: '#site-footer > div.css-z4lv1x.ellxpbm0.is_visible > div.css-1r52kff.e1rf1ndj0 > div.address-item.address_estonia > p.time.css-1btcud5-Text-Text.e1rn94vo0',
  },
  icon: {
    facebook: '[data-testid="Footer:link:facebook"]',
    linkdIn: '[data-testid="Footer:link:linkedin"]',
    instagram: '[data-testid="Footer:link:instagram"]',
    youTube: '[data-testid="Footer:link:youtube"]',
    soundcloud: '[data-testid="Footer:link:soundcloud"]',
    telegram: '[data-testid="Footer:link:telegram"]',
    twitter: '[data-testid="Footer:link:twitter"]',
    vk: '[data-testid="Footer:link:vk"]',
  }
}
